#! /bin/sh

wal -i ~/wallpapers/nord-mountain.jpg &
xsetroot -cursor_name left_ptr &
sxhkd &
dunst &
~/.config/polybar/launch.sh &
compton &
fcitx -d &

bspc monitor -d 1 2 3 4 5

bspc config border_width		2
bspc config window_gap			10	
bspc config focus_follows_pointer	false
bspc config top_padding		        25	
bspc config split_ratio			0.50
bspc config borderless_monocle	 	false
bspc config gapless_monocle	 	false
bspc config single_monocle	 	true

source "/home/k/.cache/wal/colors.sh"
bspc config active_border_color		$color1
bspc config normal_border_color		$color0
bspc config focused_border_color	$color1

bspc rule -a firefox desktop='^2'
bspc rule -a mpv desktop='^5'
