#! /bin/sh

xsetroot -cursor_name left_ptr &
feh --bg-scale ~/Wallpapers/PAPER.jpg &
sxhkd &
compton &
~/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5

bspc config border_width		2
bspc config window_gap 			8
bspc config focus_follows_pointer	false
bspc config top_padding			30
bspc config split_ratio			0.50
bspc config borderless_monocle	 	false
bspc config gapless_monocle	 	false
bspc config single_monocle	 	true

bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^5'
