#! /bin/sh

feh --bg-scale ~/Wallpapers/green-abstract.jpg &
~/dotfiles/scripts/wallblur -i ~/Wallpapers/green-abstract.jpg &
xsetroot -cursor_name left_ptr &
sxhkd &
dunst &
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5

bspc config border_width		2
bspc config window_gap			20	
bspc config focus_follows_pointer	false
bspc config top_padding			30
bspc config split_ratio			0.50
bspc config borderless_monocle	 	false
bspc config gapless_monocle	 	false
bspc config single_monocle	 	true
bspc config active_border_color		\#239862
bspc config normal_border_color		\#0a0b0e
bspc config focused_border_color	\#239862

bspc rule -a firefox desktop='^2'
